baseURL = "https://a2podcast.it/"
languageCode = "it-IT"
timeZone = "Europe/Rome"
defaultContentLanguage = "it"
title = "A2 Podcast"
enableRobotsTXT = true
enableEmoji = false

[pagination]
  pagerSize = 20

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

[taxonomies]
  tag = "tags"

[permalinks]
  episodi = "/:slug/"
  ospiti  = "/ospiti/:slug/"

[params]
  tagline        = "Tecnologia Apple per professionisti"
  description    = "Un podcast sull'uso della tecnologia Apple per professionisti. Filippo (avvocato) e Roberto (architetto) ti spiegano come ottenere il massimo dai tuoi dispositivi Apple in puntate monotematiche o con la partecipazione di ospiti"
  podcastTitle   = "A2 Podcast"
  podcastAuthor  = "Filippo Strozzi e Roberto Marin"
  podcastFeedUrl = "https://www.spreaker.com/show/6519470/episodes/feed"
  spreakerShowId = "6519470"
  podcastImage   = "/img/logo.jpg"
  network        = "Runtime Radio"
  networkUrl     = "https://runtimeradio.com"

  applePodcastsUrl = "https://podcasts.apple.com/us/podcast/a2/id1555104264"
  spreakerUrl      = "https://www.spreaker.com/podcast/a2--6519470"
  youtubeUrl       = "https://www.youtube.com/@a2podcast688/streams"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
