/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/rebuild-cron/wrangler.jsonc --include-runtime=false workers/rebuild-cron/worker-configuration.d.ts` (hash: b4d1e42fa9f74345e09cf5cfb521b1c4)
interface __BaseEnv_Env {
	DEPLOY_HOOK_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_HOOK_URL">> {}
}
